kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile-sc
provisioner: file.csi.azure.com
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
parameters:
  skuName: Standard_LRS
  location: eastus
  storageAccount: referitstorageaccount
  resourceGroup: MC_myResourceGroup_myCluster_eastus
  secretNamespace: "default"
  secretName: azure-secret
reclaimPolicy: Retain
allowVolumeExpansion: true