apiVersion: apps/v1
kind: Deployment
metadata:
  name: referit-backend-deployment
  namespace: referit
spec:
  revisionHistoryLimit: 2
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: referit-backend
  template:
    metadata:
      labels:
        app: referit-backend
    spec:
      containers:
      - name: referit-backend
        image: masterchief01/referit-backend:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 5001
        imagePullPolicy: Always
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: referit-backend-configmap
              key: PORT
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: referit-backend-configmap
              key: MONGO_URI
        - name: MONGO_TEST_URI
          valueFrom:
            configMapKeyRef:
              name: referit-backend-configmap
              key: MONGO_TEST_URI
        envFrom:
        - secretRef:
            name: referit-backend-secret
---
apiVersion: v1
kind: Service
metadata:
  name: referit-backend-service
  namespace: referit
spec:
  selector:
    app: referit-backend
  ports:
  - name: http
    port: 5001
    targetPort: 5001