apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: referit-pvc
  namespace: referit
  labels:
    app: referit
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1G
  storageClassName: ""